apiVersion: v1
kind: ServiceAccount
metadata:
  name: app2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec:
  selector:
    matchLabels:
      app: app2
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "app2"
        vault.hashicorp.com/agent-inject-secret-app-config.txt: "db/creds/readonly"
        vault.hashicorp.com/agent-inject-template-app-config.txt: |
        #  {{- with secret "db/creds/readonly" -}}
        #  postgresql://{{ .Data.username }}:{{ .Data.password }}@postgres:5432/wizard
        #  {{- end -}}
      labels:
        app: app2
    spec:
      serviceAccountName: app2
      containers:
        - name: app2
          image: jweissig/app:0.0.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres
          envFrom:
          - configMapRef:
              name: postgres-configuration
          ports:
          - containerPort: 5432
            name: postgresdb
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  labels:
    app: db
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres