services:
  vault:
    image: hashicorp/vault-enterprise:latest
    ports:
      - "8200:8200"
    environment:
      - SKIP_SETCAP="true"
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_LICENSE=$VAULT_LICENSE
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_LOG_LEVEL=info
  dc: 
    image: nicolaka/samba-domain:test
    ports:
      - "389:389"
      - "636:636"
    environment:
    - DOMAIN=hashicorp.com
    - DOMAINPASS=P@ssword1
    - INSECURELDAP="true"
